# docker run -d --name react -p 3000:3000 -v C:\Users\Blinn\Documents\rust\search_project\react_frontend:/app node:latest tail -f /dev/null
FROM node:latest
RUN npm install @react-pdf-viewer/core @react-pdf-viewer/default-layout react-pdf