---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: booksearch-deployment
spec:
  selector:
    matchLabels:
      app: pdf-app
  replicas: 1
  template:
    metadata:
      labels:
        app: pdf-app
    spec:
      hostname: booksearch
      imagePullSecrets:
      - name: blinnc-docker
      containers:
      - name: booksearch-container
        image: blinnc/search:next
        env:
        - name: BACKEND_USER
          valueFrom:
          secretKeyRef:
            name: pg-secret
            key: username
        - name: BACKEND_PASS
          valueFrom:
          secretKeyRef:
            name: pg-secret
            key: password
        - name: BACKEND_HOST
          value: "pdf-service"
        - name: OLLAMA_HOST
          value: "pdf-service"
        - name: ROCKET_ADDRESS
          value: "0.0.0.0"
        - name: ROCKET_PORT
          value: "9000"
        ports:
        - name: bs-port
          containerPort: 9000
        readinessProbe:
          httpGet:
            path: /
            port: 9000
          initialDelaySeconds: 30
          periodSeconds: 10
          timeoutSeconds: 5
          failureThreshold: 3
