---
apiVersion: gateway.networking.k8s.io/v1
kind: HTTPRoute
metadata:
  name: cb-search-http
spec:
  parentRefs:
  - name: traefik-gateway
    sectionName: http
  hostnames:
  - "search.carsonblinn.com"
  rules:
  - filters:
      - type: RequestRedirect
        requestRedirect:
          scheme: https
---
apiVersion: gateway.networking.k8s.io/v1
kind: HTTPRoute
metadata:
  name: cb-search-https
spec:
  parentRefs:
  - name: traefik-gateway
    sectionName: https
  hostnames:
  - "search.carsonblinn.com"
  rules:
  - backendRefs:
    - name: pdf-service
      port: 9000
